const initialMembers = [
    {
        memImg: "src/assets/Images/pp/George_Fernandes.jpg",
        name: 'George Fernandes',
        Designation: 'Visual Designer',
        Dept: 'Design',
        signal: true,
        op: true,
        rptimg: "src/assets/Images/pp/Steven.jpg",
        rpname: "Steven",
        sum: true,
        role: "Employee",
        email: "georgefernandes@gmail.com",
        exp: "3 Yrs 4 Mon",
        online: false,
    },
    {
        memImg: "src/assets/Images/pp/Jason.jpg",
        name: 'Jason Dominic',
        Designation: 'Full Stack Developer',
        Dept: 'Engineering',
        signal: true,
        op: true,
        rptimg: "src/assets/Images/pp/Bruce.jpg",
        rpname: "Alica Dsouza",
        sum: 0,
        role: "Employee",
        email: "dominicjason22@gmail.com",
        exp: "3 Yrs 4 Mon",
        online: true,
    },
    {
        memImg: "src/assets/Images/pp/Emilie.jpg",
        name: 'Emilie Clarke',
        Designation: 'Visual Designer',
        Dept: 'Design',
        signal: true,
        op: true,
        rptimg: "src/assets/Images/pp/Steven.jpg",
        rpname: "Steven",
        sum: true,
        role: "Employee",
        email: "emilie145@gmail.com",
        exp: "3 Yrs 4 Mon",
        online: false,
    },
    {
        memImg: "src/assets/Images/pp/Bruce_banner.jpg",
        name: 'Bruce Banner',
        Designation: 'Front End Developer',
        Dept: 'Engineering',
        signal: true,
        op: true,
        rptimg: "src/assets/Images/pp/Steven.jpg",
        rpname: "Steven",
        sum: true,
        role: "Employee",
        email: "bruce.banner@gmail.com",
        exp: "3 Yrs 4 Mon",
        online: false,
    },
    {
        memImg: "src/assets/Images/pp/Jason.jpg",
        name: 'Jason Dominic',
        Designation: 'Full Stack Developer',
        Dept: 'Engineering',
        signal: true,
        op: true,
        rptimg: "src/assets/Images/pp/Bruce.jpg",
        rpname: "Alica Dsouza",
        sum: 0,
        role: "Employee",
        email: "dominicjason22@gmail.com",
        exp: "3 Yrs 4 Mon",
        online: true,
    },
    {
        memImg: "src/assets/Images/pp/Emilie.jpg",
        name: 'Emilie Clarke',
        Designation: 'Visual Designer',
        Dept: 'Design',
        signal: true,
        op: true,
        rptimg: "src/assets/Images/pp/Steven.jpg",
        rpname: "Steven",
        sum: true,
        role: "Employee",
        email: "emilie145@gmail.com",
        exp: "3 Yrs 4 Mon",
        online: false,
    },
    {
        memImg: "src/assets/Images/pp/Bruce_banner.jpg",
        name: 'Bruce Banner',
        Designation: 'Front End Developer',
        Dept: 'Engineering',
        signal: true,
        op: true,
        rptimg: "src/assets/Images/pp/Steven.jpg",
        rpname: "Steven",
        sum: true,
        role: "Employee",
        email: "bruce.banner@gmail.com",
        exp: "3 Yrs 4 Mon",
        online: false,
    },
];

export default initialMembers;
